Render passes (pipeline/render_passes.md)
chuigda/Vulkan-Tutorial-Rust-CN pull request #37
Opened 2023-07-24 11:33 UTC by chuigda

2023-07-27 01:38 UTC, lyra-planet commented on book/src/pipeline/render_passes.md
> +这里设置的颜色附着将会被片段着色器使用，对应我们在片段着色器中的 `layout(location = 0) out vec4 outColor` 指令。
fragment,名词,计算机图形学术语,片元,另一个翻译是片段，但我认为片元更好,,

2023-07-28 01:18 UTC, flaribbit approved these changes

2023-07-28 02:56 UTC, Shimogawa requested changes

2023-07-28 02:56 UTC, Shimogawa commented on book/src/pipeline/render_passes.md
> +在创建渲染管线之前，我们还需要设置渲染过程中将会使用的帧缓冲附件（framebuffer attachments）。我们需要指定有多少颜色和深度缓冲，每个缓冲使用多少样本数，以及渲染操作将如何处理缓冲中的内容。所有这些信息都会被装进一个*渲染流程*对象中。我们将会创建一个新的函数 `create_render_pass`，并在 `App::create` 中 `create_pipeline`
多少`个`颜色和深度缓冲

2023-07-28 02:56 UTC, Shimogawa commented on book/src/pipeline/render_passes.md
> +在我们的场景中，我们只需要一个颜色附件。我们将会在 `AppData` 中创建一个 `vk::RenderPass` 字段来存放渲染流程对象：
后半句是啥？

2023-07-28 02:56 UTC, Shimogawa commented on book/src/pipeline/render_passes.md
> +在我们的场景下，我们希望在渲染新帧之前将帧缓冲清空为黑色。而 `store_op` 只有两种选择：
用中文解释 load_op 和 store_op（如果之前有那忽略这条

2023-07-28 02:56 UTC, Shimogawa commented on book/src/pipeline/render_passes.md
> +我们希望在屏幕上看到渲染出来的三角形，所以我们选择 `store_op`。
我们不是 load_op 和 store_op 都选择了吗

2023-07-28 02:56 UTC, Shimogawa commented on book/src/pipeline/render_passes.md
> +在 Vulkan 中，纹理和帧缓冲是以具有特定像素格式的 `vk::Image` 对象来表示的。不过你可以根据你在用图像做的事情改变图像中像素的布局。
不过你可以根据你在~~用~~**对**图像做的事情改变~~图像~~**内存**中像素的布局。

2023-07-28 03:13 UTC, chuigda commented on book/src/pipeline/render_passes.md
> +在我们的场景下，我们希望在渲染新帧之前将帧缓冲清空为黑色。而 `store_op` 只有两种选择：
48 行应该足够解释这一点

2023-07-28 15:14 UTC, merged

2023-07-28 15:16 UTC, Shimogawa commented on book/src/pipeline/render_passes.md
> +我们希望在屏幕上看到渲染出来的三角形，所以我们选择 `STORE`。
下面代码里用的是DONT_CARE？

2023-07-28 15:52 UTC, chuigda commented on book/src/pipeline/render_passes.md
> +我们希望在屏幕上看到渲染出来的三角形，所以我们选择 `STORE`。
那就是原作者的锅。<del>其实我翻译这篇的时候也不是太清醒，漏网之鱼了。</del>之后我自己再看一遍，然后去把作者打一顿。

2023-07-28 15:55 UTC, chuigda commented on book/src/pipeline/render_passes.md
> +我们希望在屏幕上看到渲染出来的三角形，所以我们选择 `STORE`。
下面代码里讲的是 `stencil` 的 load/store，那个是 don't care 的