Vertex buffer creation (vertex/vertex_buffer_creation.md)
chuigda/Vulkan-Tutorial-Rust-CN pull request #46
Opened 2023-07-31 02:27 UTC by lyra-planet

2023-07-31 04:06 UTC, chuigda commented
根据 TERMINOLOGY.csv，我们对 “buffer” 的翻译统一为“缓冲”，不带“区”这个字

2023-07-31 04:06 UTC, chuigda requested changes
根据 TERMINOLOGY.csv，我们对 “buffer” 的翻译统一为“缓冲”，不带“区”这个字

2023-07-31 06:17 UTC, lyra-planet commented
> 根据 TERMINOLOGY.csv，我们对 “buffer” 的翻译统一为“缓冲”，不带“区”这个字

前一篇中有个staging buffer写成暂存缓冲区了:( ，要不要我改下

2023-07-31 07:20 UTC, chuigda commented on book/src/SUMMARY.md
>  - [Staging buffer](./vertex/staging_buffer.md)
中文里很少有“动词用作名词”这种做法，要不我们颠倒下语序写成“创建顶点缓冲”这样？

2023-07-31 07:34 UTC, chuigda reviewed
还有一些地方需要打磨，我会亲自指挥、亲自部署

2023-07-31 07:34 UTC, chuigda commented on book/src/vertex/vertex_buffer_creation.md
> +在Vulkan中，缓冲是用于存储可被图形卡读取的任意数据的内存区域。它们可以用于存储顶点数据，这正是我们将在本章中所做的，但它们也可以用于许多其他目的，这些将在以后的章节中探讨。与我们到目前为止处理过的Vulkan对象不同，缓冲不会自动为自己分配内存。前面章节中的工作已经表明，Vulkan API将程序员置于几乎所有事物的控制下，内存管理就是其中之一。
图形卡 -> 显卡，之后我看要不要TERMINOLOGY.csv里补一份

2023-07-31 07:34 UTC, chuigda commented on book/src/vertex/vertex_buffer_creation.md
> +和交换链中的图像一样，缓冲也可以由特定队列族拥有，或者在多个队列之间共享。由于缓冲仅将在图形队列中使用，因此我们可以使用独占访问。
应该是在**多个队列族**中共享

2023-07-31 07:34 UTC, chuigda commented on book/src/vertex/vertex_buffer_creation.md
> +`flags` 参数用于配置稀疏缓冲内存，这在当前情况下并不相关。您可以省略此字段的构建方法，从而将其设置为默认值（空标志集）。
这在当前情况下并不相关 -> 现在我们还不用关心这个。

---

构建方法 -> 生成器(builder)方法

我有点怀疑把 builder 翻译成生成器是不是正确的决定了，不过这个之后再说

2023-07-31 07:34 UTC, chuigda commented on book/src/vertex/vertex_buffer_creation.md
> +现在，我们可以使用 `create_buffer` 创建缓冲。首先，定义一个 `AppData` 字段来保存缓冲句柄，并称其为 `vertex_buffer`。
这里调整语序，我亲自微操

2023-07-31 07:34 UTC, chuigda commented on book/src/vertex/vertex_buffer_creation.md
> +接下来添加对 `create_buffer` 的调用：
这里意译，我亲自微操

2023-07-31 07:34 UTC, chuigda commented on book/src/vertex/vertex_buffer_creation.md
> +在下一章中，我们将介绍一种不同的将顶点数据复制到顶点缓冲的方法，这将导致更好的性能，但需要更多的工作。
介绍一种不同的 -> 介绍另一种

2023-08-01 01:10 UTC, chuigda commented on book/src/vertex/vertex_buffer_creation.md
> +在Vulkan中，缓冲是用于存储可被图形卡读取的任意数据的内存区域。它们可以用于存储顶点数据，这正是我们将在本章中所做的，但它们也可以用于许多其他目的，这些将在以后的章节中探讨。与我们到目前为止处理过的Vulkan对象不同，缓冲不会自动为自己分配内存。前面章节中的工作已经表明，Vulkan API将程序员置于几乎所有事物的控制下，内存管理就是其中之一。
TERMINOLOGY.csv里早就有了，Lyra全责

2023-08-01 02:52 UTC, Shimogawa commented on book/src/vertex/vertex_buffer_creation.md
> +在下一章中，我们将介绍一种不同的将顶点数据复制到顶点缓冲的方法，这将导致更好的性能，但需要更多的工作。
导致一般用于负面结果

2023-08-05 09:25 UTC, merged