Depth buffering (model/depth_buffering.md)
chuigda/Vulkan-Tutorial-Rust-CN pull request #74
Opened 2023-09-28 15:38 UTC by CousinZe

Close #72

2023-09-30 03:19 UTC, chuigda requested changes

2023-09-30 03:19 UTC, chuigda commented on book/src/model/depth_buffering.md
> +和颜色附件一样，深度附件也是基于图像的。区别在于交换链不会自动为我们创建深度图像。我们只需要一个深度图像，因为同时只有一个绘制操作在运行。深度图像同样需要三个资源：图像、内存和图像视图。
我不是很确定，但我觉得这里的语义应该是同时只有一个绘制操作在进行深度检测。前文已经说过 Vulkan 的优势之一就在于只要渲染的多个阶段不抢资源，就能同时渲染处于不同阶段的多个帧。我们可以现在就翻 specification 查证这个问题并且*去跟 Overv 吵架*，也可以等第一轮翻译完再修。

2023-09-30 03:19 UTC, chuigda commented on book/src/model/depth_buffering.md
> +创建深度图像非常直观。它应该具有以下属性：由交换链范围定义的与颜色附件相同的分辨率、适用于深度附件的图像用法、最佳平铺模式、设备本地内存。唯一的问题是：深度图像的正确格式是什么？格式必须包含一个深度分量，由 `vk::Format` 变体中的 `D??_` 表示。
```suggestion
创建深度图像非常直观。深度图像应该具有以下属性：由交换链范围定义的、与颜色附件相同的分辨率，适用于深度附件的图像用法，最佳平铺模式，并且存储在设备本地内存中。唯一的问题是：深度图像的正确格式是什么？格式必须包含一个深度分量，由 `vk::Format` 变体中的 `D??_` 表示。
```

2023-09-30 03:19 UTC, chuigda commented on book/src/model/depth_buffering.md
> +不同于纹理图像的是，我们并不一定需要一个特定的像素格式，因为我们不会直接在程序中访问深度图像中的像素。深度图像中的像素只要有一个合理的精度就行。现实世界中的应用程序通常都使用至少 24 位的精度，有几种格式符合这个要求：
```suggestion
不同于纹理图像的是，我们并不需要一个特定的像素格式，因为我们不会直接在程序中访问深度图像中的像素。深度图像中的像素只要有一个合理的精度就行。现实世界中的应用程序通常都使用至少 24 位的精度，有几种格式符合这个要求：
```

2023-09-30 03:19 UTC, chuigda commented on book/src/model/depth_buffering.md
> +更新所有调用点，使用正确的 aspect：
```suggestion
更新所有调用点，传递正确的 `aspects`：
```

2023-09-30 03:19 UTC, chuigda commented on book/src/model/depth_buffering.md
> +我们不需要显式地将图像的布局转换为深度附件，因为我们将在渲染通道中处理这个问题。然而，为了完整起见，我仍然会在本节中描述这个过程。如果你愿意，你可以跳过它。
```suggestion
我们不需要显式地将图像的布局转换为深度附件，因为我们将在渲染流程中处理这个问题。然而，为了完整起见，我仍然会在本节中描述这个过程。如果你愿意，你可以跳过它。
```

2023-10-01 15:54 UTC, CousinZe commented on book/src/model/depth_buffering.md
> +和颜色附件一样，深度附件也是基于图像的。区别在于交换链不会自动为我们创建深度图像。我们只需要一个深度图像，因为同时只有一个绘制操作在运行。深度图像同样需要三个资源：图像、内存和图像视图。
第一轮翻译完再说吧，specification 我翻了一下，看起来是个很头疼的问题

2023-10-02 07:41 UTC, merged