Image view and sampler (texture/image_view_and_sampler.md)
chuigda/Vulkan-Tutorial-Rust-CN pull request #75
Opened 2023-09-29 04:03 UTC by chuigda

Closes #69

2023-09-29 13:10 UTC, CousinZe requested changes

2023-09-29 13:10 UTC, CousinZe commented on book/src/texture/image_view_and_sampler.md
> +如果要使用各向异性过滤，我们需要指定两个字段。除非遇到了性能问题，不然没理由不启用各向异性过滤。`max_anisotropy` 字段限制了用于计算最终颜色的纹素样本的数量。将其设为较低的值能带来更好的性能，但也会降低渲染的质量。目前没有任何图形硬件会使用超过 16 个样本，因为就算使用了超过这个数量的样本，也不会有什么区别。
consider: 就算使用了超过这个数量的样本，**效果上**也不会有什么区别

2023-09-29 13:10 UTC, CousinZe commented on book/src/texture/image_view_and_sampler.md
> +`unnormalized_coordinates` 字段指定了你想要使用哪种坐标系来寻址图像中的纹素。如果这个字段是 `true`，那么你可以简单地使用 `[0, width)` 和 `[0, height)` 范围内的坐标。如果是 `false`，那么纹素将使用所有轴上的 `[0, 1)` 范围来寻址。现实世界中的应用几乎总是使用标准化坐标，因为这样就可以用完全相同的坐标使用不同分辨率的纹理
读起来怪怪的，再看看

2023-09-29 13:10 UTC, CousinZe commented on book/src/texture/image_view_and_sampler.md
> +采样器的功能现在已经完全定义了。添加一个 `AppData` 字段来保存采样器对象的句柄：
> 采样器的功能现在已经完全定义了。

这句读起来怪怪的，再看看

2023-09-29 14:35 UTC, flaribbit commented on book/src/texture/image_view_and_sampler.md
> +在本章中，我们将会创建两个新的资源，这些资源是图形管线中采样图像所必需的。第一个资源我们在之前使用交换链图像时已经见过了，但是第二个资源是全新的，它与着色器如何从图像中读取像素有关。
> consider: 我们将会创建两个新的**图形管线中采样图像所必须的**资源

gud

2023-09-29 14:35 UTC, flaribbit commented on book/src/texture/image_view_and_sampler.md
> +现在我们创建一个 `create_texture_sampler` 函数来设置一个采样器对象。之后我们会在着色器中使用这个采样器来从纹理中读取颜色。
一个 -> 这样的？

2023-09-29 14:35 UTC, flaribbit commented on book/src/texture/image_view_and_sampler.md
> +`mag_filter` 和 `min_filter` 字段指定了如何插值放大或缩小的纹素。放大涉及上面描述的采样过密问题，而缩小涉及到采样过疏。选择项是 `vk::Filter::NEAREST` 和 `vk::Filter::LINEAR`，对应于上面图像中演示的模式。
对应于？对应？

2023-09-29 14:35 UTC, flaribbit commented on book/src/texture/image_view_and_sampler.md
> +如果要使用各向异性过滤，我们需要指定两个字段。除非遇到了性能问题，不然没理由不启用各向异性过滤。`max_anisotropy` 字段限制了用于计算最终颜色的纹素样本的数量。将其设为较低的值能带来更好的性能，但也会降低渲染的质量。目前没有任何图形硬件会使用超过 16 个样本，因为就算使用了超过这个数量的样本，也不会有什么区别。
不是可以忽略吗）

2023-09-29 14:35 UTC, flaribbit commented on book/src/texture/image_view_and_sampler.md
> +`unnormalized_coordinates` 字段指定了你想要使用哪种坐标系来寻址图像中的纹素。如果这个字段是 `true`，那么你可以简单地使用 `[0, width)` 和 `[0, height)` 范围内的坐标。如果是 `false`，那么纹素将使用所有轴上的 `[0, 1)` 范围来寻址。现实世界中的应用几乎总是使用标准化坐标，因为这样就可以用完全相同的坐标使用不同分辨率的纹理
虽然原文是这样，但很怪，这不就是是否使用未标准化的坐标吗。

2023-10-01 13:02 UTC, chuigda commented on book/src/texture/image_view_and_sampler.md
> +采样器的功能现在已经完全定义了。添加一个 `AppData` 字段来保存采样器对象的句柄：
我读了一下感觉没什么问题，这就先这样

2023-10-01 13:02 UTC, chuigda commented on book/src/texture/image_view_and_sampler.md
> +现在我们创建一个 `create_texture_sampler` 函数来设置一个采样器对象。之后我们会在着色器中使用这个采样器来从纹理中读取颜色。
我全都要！

2023-10-01 13:09 UTC, chuigda commented
> 虽然原文是这样，但很怪，这不就是是否使用未标准化的坐标吗。 

再读一下看看，这样应该 Ok 了

2023-10-01 15:38 UTC, CousinZe commented on book/src/texture/image_view_and_sampler.md
> +我省略了显式的 `components` 初始化，因为 `vk::ComponentSwizzle::IDENTITY` 已经定义为 `0` 了。通过调用 `create_image_view` 来完成图像视图的创建：
那 byd 你倒是说明一下啊

2023-10-01 15:44 UTC, merged