Combined image sampler (texture/combined_image_sampler.md)
chuigda/Vulkan-Tutorial-Rust-CN pull request #77
Opened 2023-09-29 10:54 UTC by chuigda

Closes #71

2023-10-01 16:15 UTC, CousinZe requested changes

2023-10-01 16:15 UTC, CousinZe commented on book/src/texture/combined_image_sampler.md
> +我们在 uniform 缓冲部分第一次认识了描述符。在本章中我们将看到一种新的描述符类型：*组合图像采样器*。这种描述符使得着色器可以通过像我们在上一章中创建的采样器对象来访问图像资源。
```suggestion
我们在 uniform 缓冲部分第一次认识了描述符。在本章中我们将看到一种新的描述符：*组合图像采样器*。这种描述符使得着色器可以通过像我们在上一章中创建的采样器对象来访问图像资源。
```

2023-10-01 16:15 UTC, CousinZe commented on book/src/texture/combined_image_sampler.md
>  ## Updating the descriptors
你忘了翻译这个

2023-10-01 16:15 UTC, CousinZe commented on book/src/texture/combined_image_sampler.md
> +记得设置 `stage_flags` 以指示我们将会在片元着色器中使用组合图像采样器描述符。这是片元的颜色将会被确定的地方。在顶点着色器中使用纹理采样是可能的，例如通过[高度图](https://en.wikipedia.org/wiki/Heightmap)动态地变形顶点网格。
```suggestion
记得将 `stage_flags` 设为 `vk::ShaderStageFlags::FRAGMENT`，以指示我们将会在片元着色器中使用组合图像采样器描述符 —— 这是片元的颜色将会被确定的地方。在顶点着色器中使用纹理采样是可能的，例如通过[高度图](https://en.wikipedia.org/wiki/Heightmap)动态地变形顶点网格。
```

2023-10-01 16:15 UTC, CousinZe commented on book/src/texture/combined_image_sampler.md
> +和逐顶点颜色异样，`fragTexCoord` 值也会被光栅化器在正方形区域内平滑插值。我们可以通过让片元着色器将纹理坐标作为颜色输出来可视化这一点：
```suggestion
和逐顶点颜色一样，`fragTexCoord` 值也会被光栅化器在正方形区域内平滑插值。我们可以通过让片元着色器将纹理坐标作为颜色输出来可视化这一点：
```

2023-10-01 16:15 UTC, CousinZe commented on book/src/texture/combined_image_sampler.md
> +你也可以用定点颜色来改变纹理颜色：
```suggestion
你也可以用顶点颜色来改变纹理颜色：
```

2023-10-02 20:55 UTC, Shimogawa commented on book/src/texture/combined_image_sampler.md
> +记得将 `stage_flags` 设为 `vk::ShaderStageFlags::FRAGMENT`，以指示我们将会在片元着色器中使用组合图像采样器描述符 —— 这是片元的颜色将会被确定的地方。在顶点着色器中使用纹理采样是可能的，例如通过[高度图](https://en.wikipedia.org/wiki/Heightmap)动态地变形顶点网格。
使顶点网格变形/改变顶点网格的形状

2023-10-02 20:59 UTC, Shimogawa commented on book/src/texture/combined_image_sampler.md
> +我们必须创建一个更大的描述符池，在 `vk::DescriptorPoolCreateInfo` 中添加另一个 `vk::DescriptorType::COMBINED_IMAGE_SAMPLER` 类型的 `vk::DescriptorPoolSize`，从而为组合图像采样器的分配腾出空间。转到 `create_descriptor_pool` 函数并修改它以包含此描述符的 `vk::Des
你或许想要表达：并修改其中的 `vk::DescriptorPoolSize` 使其包含组合图像采样器描述符。

2023-10-02 21:03 UTC, Shimogawa commented on book/src/texture/combined_image_sampler.md
> +我在这里分离了 RGB 和 alpha 通道，以免缩放 alpha 通道。
依据土坯公司的翻译，应该是「Alpha 通道」

2023-10-03 04:46 UTC, chuigda commented on book/src/texture/combined_image_sampler.md
> +我们必须创建一个更大的描述符池，在 `vk::DescriptorPoolCreateInfo` 中添加另一个 `vk::DescriptorType::COMBINED_IMAGE_SAMPLER` 类型的 `vk::DescriptorPoolSize`，从而为组合图像采样器的分配腾出空间。转到 `create_descriptor_pool` 函数并修改它以包含此描述符的 `vk::Des
不是的，这里确实是新建了一个 `vk::DescriptorPoolSize`（*include another descriptor pool size in the `vk::DescriptorPoolCreateInfo`, for the combined image sampler.*)。

2023-10-03 04:49 UTC, chuigda commented on book/src/texture/combined_image_sampler.md
> +我在这里分离了 RGB 和 alpha 通道，以免缩放 alpha 通道。
我们之后再考虑统一解决这里的问题，因为不止一处被写作 alpha。<del>而且我不是很想按土坯公司的来。</del>

2023-10-03 04:52 UTC, merged