Push constants (dynamic/push_constants.md)
chuigda/Vulkan-Tutorial-Rust-CN pull request #84
Opened 2023-10-02 20:03 UTC by chuigda

Closes #83

2023-10-03 08:47 UTC, CousinZe requested changes

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +目前为止我们在教程中创建的场景都是静态的。虽然我们可以操作提供模型、视图和投影（MVP）矩阵的 uniform 缓冲来旋转和移动模型，但是我们不能改变*渲染什么*。这是因为程序在初始化的过程中、分配和记录指令缓冲d的时候就已经决定了要渲染什么。
```suggestion
目前为止我们在教程中创建的场景都是静态的。虽然我们可以操作提供模型、视图和投影（MVP）矩阵的 uniform 缓冲来旋转和移动模型，但是我们不能改变*渲染什么*。这是因为程序在初始化的过程中分配和记录指令缓冲的时候就已经决定了要渲染什么。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +之前我们已经在使用另一种能将动态数据提供给顶点着色器的 Vulkan 特性了：那就是 uniform 缓冲。在渲染每一帧时，`App::update_uniform_buffer` 方法都会为模型的当前旋转角度计算更新之后的 MVP 矩阵，并将这些矩阵复制到 uniform 缓冲中。然后顶点着色器从 uniform 缓冲中读取这些矩阵，以确定模型的顶点在屏幕上的位置。
```suggestion
之前我们已经在使用另一种能将动态数据提供给顶点着色器的 Vulkan 特性了：那就是 uniform 缓冲。在渲染每一帧时，`App::update_uniform_buffer` 方法都会根据模型当前的旋转角度计算出新的 MVP 矩阵，并将这些矩阵复制到 uniform 缓冲中。然后顶点着色器从 uniform 缓冲中读取这些矩阵，以确定模型的顶点在屏幕上的位置。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +当然，这里有一个限制：使用推送常量提供给着色器的数据量有一个*非常*有限的最大值。这个最大值因设备而异，由 `vk::PhysicalDeviceLimits` 的 `max_push_constants_size` 字段以字节为单位指定。Vulkan 要求这个限制至少为[128字节](https://www.khronos.org/registry/vulkan/specs/1.2/html/
```suggestion
当然，这里有一个限制：使用推送常量提供给着色器的数据量有一个*非常*有限的最大值。这个最大值因设备而异，由 `vk::PhysicalDeviceLimits` 的 `max_push_constants_size` 字段以字节为单位指定。Vulkan 要求这个限制至少为[128字节](https://www.khronos.org/registry/vulkan/specs/1.2/html/chap33.html#limits-minmax)（见表 32），但实际设备上的最大值也不会比 128 高多少。即使是 RTX 3080 这样的高端硬件，这个最大值也只有 256 字节。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +如果我们想用推送常量来向矩阵提供我们的 MVP 矩阵，那么我们马上就会撞倒这个限制。MVP 矩阵太大了，无法被可靠地放入推送常量中：每个矩阵是 64 字节（16 × 4 字节浮点数），总共 192 字节。当然，我们可以写两套代码，一套用于处理推送常量 >= 192 字节的设备，另一套用于处理无法满足这个需求的设备，但是我们还有更简单的方法。
```suggestion
如果我们想用推送常量来向矩阵提供我们的 MVP 矩阵，那么我们马上就会撞到这个限制。MVP 矩阵太大了，无法被可靠地放入推送常量中：每个矩阵是 64 字节（16 × 4 字节浮点数），总共 192 字节。当然，我们可以写两套代码，一套用于处理推送常量 >= 192 字节的设备，另一套用于处理无法满足这个需求的设备，但是我们还有更简单的方法。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +为什么只用推送常量提供模型矩阵呢？在 `App::update_uniform_buffer` 方法中，你可以注意到 `model` 矩阵随着 `time` 的增加，在每一帧中都会有所改变；`view` 矩阵是静态的；而 `proj` 矩阵只会在窗口大小发生变化的时候改变。这就使得我们可以只在窗口大小发生变化的时候更新包含视图和投影矩阵的 uniform 缓冲，而使用推送常量来提供不断变化的模型
```suggestion
为什么只将推送常量用于模型矩阵呢？在 `App::update_uniform_buffer` 方法中，你可以注意到 `model` 矩阵随着 `time` 的增加，在每一帧中都会有所改变，而`view` 矩阵是静态的，`proj` 矩阵则只会在窗口大小发生变化的时候改变。这就使得我们可以只在窗口大小发生变化时更新包含视图和投影矩阵的 uniform 缓冲，而将推送常量用于不断变化的模型矩阵。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +当然，在实际的应用程序中，试图矩阵不太可能是静态的。例如，如果你在构建一个第一人称游戏，`view` 矩阵可能会随着玩家在游戏世界中移动而快速变化。然而，即使视图和投影矩阵每一帧都发生改变，至少它们也会在你渲染的所有模型之间共享。这意味着你可以继续每一帧更新 uniform 缓冲，以提供共享的视图和投影矩阵，并使用推送常量来为场景中的每个模型提供模型矩阵。
```suggestion
当然，在实际的应用程序中，视图矩阵不太可能是静态的。例如，如果你在构建一个第一人称游戏，`view` 矩阵可能会随着玩家在游戏世界中移动而快速变化。然而，即使视图和投影矩阵每一帧都发生改变，至少它们也会在你渲染的所有模型之间共享。也就是说你可以在每一帧中更新 uniform 缓冲，以提供共享的视图和投影矩阵，并为场景中每个模型的模型矩阵使用推送常量。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +从 `UniformBufferObject` 结构体中移除 `model`，因为我们将从现在开始将模型矩阵指定为推送常量。
```suggestion
从 `UniformBufferObject` 结构体中移除 `model`，因为从现在开始我们会为模型矩阵使用推送常量。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +我们需要在图形管线的布局中进行描述，将我们的新推送常量告知 Vulkan。在 `create_pipeline` 函数中，你可以看到我们已经将描述符集合布局提供给了 `create_pipeline_layout`。这个描述符集合布局描述了我们着色器中使用的 uniform 缓冲对象和纹理采样器，我们需要使用 `vk::PushConstantRange` 来描述图形管线中着色器将要访问的任何推
```suggestion
我们需要更新图形管线的布局，将我们的新推送常量告知 Vulkan。在 `create_pipeline` 函数中，你可以看到我们之前已经将描述符集合布局提供给了 `create_pipeline_layout`。描述符集合布局描述了我们着色器中使用的 uniform 缓冲对象和纹理采样器，而现在我们需要使用推送常量范围 `vk::PushConstantRange` 来描述图形管线中着色器将要访问的推送常量。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +这里的推送常量范围制订了顶点着色器访问的推送常量可以在提供给图形管线的推送常量的开头找到，大小相当于一个 `mat4`。
```suggestion
这里的推送常量范围说明了顶点着色器访问的推送常量可以在提供给图形管线的推送常量的开头找到，大小相当于一个 `mat4`。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +有了这些，我们就可以开始将模型矩阵推送到顶点着色器了。推送常量会被直接记录到提交给 GPU 的指令缓冲中，这就是为什么它们如此快速，也是为什么它们的大小如此有限的原因。
```suggestion
有了这些，我们就可以开始将模型矩阵推送到顶点着色器了。推送常量会被直接记录到提交给 GPU 的指令缓冲中，这就是为什么它们如此快速，这也解释了为什么它们的大小如此有限。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +如果你现在运行程序，你会看到熟悉的模型，但是它不再旋转了！我们不再在每一帧中更新 uniform 缓冲对象中的模型矩阵，而是将其编码到指令缓冲中，正如之前所讨论的，指令缓冲永远不会被更新。这进一步凸显了我们需要以某种方式更新指令缓冲的需求，这个话题将在下一章中讨论。现在，让我们通过在片元着色器中添加一个推送常量来结束本章。
```suggestion
如果你现在运行程序，你会看到熟悉的模型，但是它不再旋转了！我们不再在每一帧中更新 uniform 缓冲对象中的模型矩阵，而是将其编码到指令缓冲中，正如之前所讨论的，指令缓冲永远不会被更新。这进一步凸显了以某种方式更新指令缓冲的需求，这个话题将在下一章中讨论。现在，让我们在片元着色器中再添加一个推送常量，然后结束本章。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +最后，在 `create_command_buffers` 中，在模型矩阵的调用之后，再添加一个 `cmd_push_constants` 的调用。
```suggestion
最后，在 `create_command_buffers` 中，在为模型矩阵调用 `cmd_push_constants` 之后，再添加一个 `cmd_push_constants` 的调用。
```

2023-10-03 08:47 UTC, CousinZe commented on book/src/dynamic/push_constants.md
> +回看[固定功能](../pipeline/fixed_functions.html#color-blending)那一章，我们讨论过如果要渲染透明几何体，需要做什么来设置 alpha 混合。然而，那时我们禁用了 alpha 混合。在 `create_pipeline` 函数中，更新 `vk::PipelineColorBlendAttachmentState`，以启用 alpha 混合，就像那一
```suggestion
回看[固定功能](../pipeline/fixed_functions.html#color-blending)那一章，我们讨论过如果要渲染透明几何体，就需要设置阿尔法合成。然而，那时我们禁用了阿尔法合成。所以现在我们要在 `create_pipeline` 函数中，更新 `vk::PipelineColorBlendAttachmentState`，以启用阿尔法合成，就像那一章中描述的那样。
```

2023-10-05 09:56 UTC, flaribbit commented on book/src/dynamic/push_constants.md
> +# 推式常量
不是 推送常量 吗

2023-10-05 09:56 UTC, flaribbit commented on book/src/dynamic/push_constants.md
> +为什么只将推送常量用于模型矩阵呢？在 `App::update_uniform_buffer` 方法中，你可以注意到 `model` 矩阵随着 `time` 的增加，在每一帧中都会有所改变，而`view` 矩阵是静态的，`proj` 矩阵则只会在窗口大小发生变化的时候改变。这就使得我们可以只在窗口大小发生变化时更新包含视图和投影矩阵的 uniform 缓冲，而将推送常量用于不断变化的模型矩阵。
空格 view

2023-10-05 09:56 UTC, flaribbit commented on book/src/dynamic/push_constants.md
> +当然，在实际的应用程序中，视图矩阵不太可能是静态的。例如，如果你在构建一个第一人称游戏，`view` 矩阵可能会随着玩家在游戏世界中移动而快速变化。然而，即使视图和投影矩阵每一帧都发生改变，至少它们也会在你渲染的所有模型之间共享。也就是说你可以在每一帧中更新 uniform 缓冲，以提供共享的视图和投影矩阵，并为场景中每个模型的模型矩阵使用推送常量。
并使用推送常量来 xxx

2023-10-05 10:03 UTC, merged