Recycling command buffers (dynamic/recycling_command_buffers.md)
chuigda/Vulkan-Tutorial-Rust-CN pull request #86
Opened 2023-10-02 20:32 UTC by chuigda

Closes #85

2023-10-03 09:14 UTC, CousinZe requested changes

2023-10-03 09:14 UTC, CousinZe commented on book/src/dynamic/recycling_command_buffers.md
> +在 `update_command_buffer` 的开头，将原先指令缓冲使用的内存返还给指令池，然后释放它。
```suggestion
在 `update_command_buffer` 的开头释放原先的指令缓冲，将其使用的内存返还给指令池。
```

2023-10-03 09:14 UTC, CousinZe commented on book/src/dynamic/recycling_command_buffers.md
> +我们把标志换成 `vk::CommandPoolCreateFlags::TRANSIENT`，这会告诉 Vulkan，我们将使用这个指令池分配的指令缓冲是“短暂的”，也就是说，它会非常短命。
```suggestion
我们把标志换成 `vk::CommandPoolCreateFlags::TRANSIENT`，这会告诉 Vulkan，我们将使用这个指令池分配的指令缓冲是“稍纵即逝的”，也就是说，这些指令缓冲会非常短命。
```

2023-10-03 09:14 UTC, CousinZe commented on book/src/dynamic/recycling_command_buffers.md
> +和 `vk::CommandBufferUsageFlags::ONE_TIME_SUBMIT` 一样，这个标志不会影响我们程序的正确性，但是它可能会让 Vulkan 驱动更好地优化对我们短命的指令缓冲的处理。
```suggestion
和 `vk::CommandBufferUsageFlags::ONE_TIME_SUBMIT` 一样，这个标志不会影响我们程序的正确性，但是它可能会让 Vulkan 驱动更好地优化对短命的指令缓冲的处理。
```

2023-10-03 09:14 UTC, CousinZe commented on book/src/dynamic/recycling_command_buffers.md
> +接着我们来看看重置整个指令池，这会一举重置我们所有的活动指令缓冲。
```suggestion
接着我们来看看重置整个指令池，这会一举重置所有存活的指令缓冲。
```

2023-10-03 09:14 UTC, CousinZe commented on book/src/dynamic/recycling_command_buffers.md
> +我们可以继续沿着这条路走下去，但这样的话我们的程序就不能并行渲染多个帧了。保持这种能力很重要，因为正如在 [`Rendering and presentation` 章节](../drawing/rendering_and_presentation.html#frames-in-flight)中提到的，这可以让我们更好地利用硬件，因为 CPU 会花费更少的时间等待 GPU，反之亦然。
```suggestion
我们可以继续沿着这条路走下去，但这样的话我们的程序就不能并行渲染多个帧了。保持多帧并行渲染的能力很重要，因为正如在 [渲染与呈现](../drawing/rendering_and_presentation.html#frames-in-flight)那一章里提到的，这可以让我们更好地利用硬件，因为 CPU 会花费更少的时间等待 GPU，反之亦然。
```

2023-10-03 09:14 UTC, CousinZe commented on book/src/dynamic/recycling_command_buffers.md
> +最后，在 `App::destroy_swapchain` 中删除对 `free_command_buffers` 的调用。这个调用现在会错误地尝试将分配给每帧指令缓冲的内存返还给全局指令池，尽管这些指令缓冲不再是从这个指令池分配的。如果保留这段代码，当窗口大小改变或者强制重新创建交换链时，我们的程序很可能会崩溃。我们不再需要管理单个指令缓冲的删除，因为我们现在是在指令池级别管理这个。
```suggestion
最后，在 `App::destroy_swapchain` 中删除对 `free_command_buffers` 的调用。这个调用会错误地尝试将分配给每帧指令缓冲的内存返还给全局指令池，而现在这些指令缓冲并不是从全局指令池指令池分配的。如果保留这段代码，当窗口大小改变或者强制重新创建交换链时，我们的程序很可能会崩溃。我们不再需要管理单个指令缓冲的删除，因为我们现在是在指令池级别管理这个。
```

2023-10-05 09:32 UTC, chuigda commented on book/src/dynamic/recycling_command_buffers.md
> +我们要注意，在调用 `update_command_buffer` 时要多加小心。如果一个指令缓冲仍然在渲染一个之前已经提交的帧，重置这个指令缓冲会引发严重的问题。这个问题在 [`Descriptor set layout and buffer` 章节](../uniform/descriptor_set_layout_and_buffer.html#updating-uniform-data)
问题不大，第一版先这样，后面再调整

2023-10-05 13:40 UTC, Shimogawa commented on book/src/dynamic/recycling_command_buffers.md
> +# 重用指令缓冲
重用/复用/（指令缓冲的）再利用？以下 ditto

2023-10-05 13:44 UTC, Shimogawa commented on book/src/dynamic/recycling_command_buffers.md
> +将 `update_command_buffer` 开头用来重置指令缓冲的代码替换为用新的指令缓冲替换之前的指令缓冲的代码。
这句话绕晕了

2023-10-05 14:20 UTC, chuigda commented on book/src/dynamic/recycling_command_buffers.md
> +将 `update_command_buffer` 开头用来重置指令缓冲的代码替换为用新的指令缓冲替换之前的指令缓冲的代码。
现在再读下试试，没问题了就点 Resolve（

2023-10-05 14:20 UTC, chuigda commented on book/src/dynamic/recycling_command_buffers.md
> +# 重用指令缓冲
先用“重用”吧。说实话这章 Kyle Mayes 的思路不是特别好，太拘泥于内存的 recycling 了，并且很多东西甚至不能说是 reuse，而是 free 了再 create 个新的。不过我们下一轮再解决这个问题。

2023-10-05 15:54 UTC, merged